### ISSUE TITLE
Building Dishes page

### ISSUE THREAD

**Issue by Sanad-Alshobaki** [202309-EKTA-JO-FSW/capstone-team-3-2#2]
start building the project dishes page
** Remember to use pagination
You will find the design here:
[Uizard_Design](https://app.uizard.io/prototypes/EO4pre8Y6BhMwaXK4mJr)

**Comment by Wajd-AlKayyali** [comment]
I am facing issue with rendering the public images maybe the URL needs to be in a certain format. 
but any way it can be fixed once the data is coming from the BE.

here is the link for the images https://drive.google.com/drive/folders/1jEaiZlA6Y4cqAjjiiQJNB4pzdKZozXHi.
